// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeploenergetikaKursovaya.Data;

#nullable disable

namespace TeploenergetikaKursovaya.Migrations
{
    [DbContext(typeof(TeploDBContext))]
    [Migration("20250524120000_AddLocalResistanceDataPoints")]
    partial class AddLocalResistanceDataPoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.DotMC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ComponentDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("ComponentName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DotMCs");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.KVoA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<double>("KinematicViscosity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("KVoAs");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.LRC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeofLR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTabular")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ValueofLR")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LRCs");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.ResistanceDataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ParamX")
                        .HasColumnType("REAL");

                    b.Property<double>("ParamY")
                        .HasColumnType("REAL");

                    b.Property<int>("ResistanceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ZetaValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ResistanceId", "ParamX", "ParamY")
                        .IsUnique();

                    b.ToTable("ResistanceDataPoints");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.Roughness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EquivalentRoughness")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roughnesses");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.UserPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserPresets");
                });

            modelBuilder.Entity("Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CustomRoughness")
                        .HasColumnType("REAL");

                    b.Property<double>("GasFlow")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightDifference")
                        .HasColumnType("REAL");

                    b.Property<string>("HeightDirection")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionsData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TemperatureLossPerMeter")
                        .HasColumnType("REAL");

                    b.Property<double>("TgasInitial")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.ResistanceDataPoint", b =>
                {
                    b.HasOne("TeploenergetikaKursovaya.Data.LRC", "Resistance")
                        .WithMany("DataPoints")
                        .HasForeignKey("ResistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resistance");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.LRC", b =>
                {
                    b.Navigation("DataPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
