// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeploenergetikaKursovaya.Data;

#nullable disable

namespace TeploenergetikaKursovaya.Migrations
{
    [DbContext(typeof(TeploDBContext))]
    [Migration("20250502143405_AddAllTables")]
    partial class AddAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.DotMC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ComponentDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("ComponentName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DotMCs");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.KVoA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<double>("KinematicViscosity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("KVoAs");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.LRC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeofLR")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValueofLR")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LRCs");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.Roughness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<double>("EquivalentRoughness")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roughnesses");
                });

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<double>("GasFlow")
                        .HasColumnType("REAL");

                    b.Property<double>("GeometricPressureDrop")
                        .HasColumnType("REAL");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightDifference")
                        .HasColumnType("REAL");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PressureDropFriction")
                        .HasColumnType("REAL");

                    b.Property<double>("PressureDropLocal")
                        .HasColumnType("REAL");

                    b.Property<double>("SectionLength")
                        .HasColumnType("REAL");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TemperatureLossPerMeter")
                        .HasColumnType("REAL");

                    b.Property<double>("TgasInitial")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPressureDrop")
                        .HasColumnType("REAL");

                    b.Property<double?>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
