// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeploenergetikaKursovaya.Data;

#nullable disable

namespace TeploenergetikaKursovaya.Migrations
{
    [DbContext(typeof(TeploDBContext))]
    partial class TeploDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TeploenergetikaKursovaya.Data.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("GasFlowRate")
                        .HasColumnType("REAL");

                    b.Property<double>("SectionLength")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureLossPerMeter")
                        .HasColumnType("REAL");

                    b.Property<double>("TgasInitial")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
