// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VKR_Russkin.Data;

#nullable disable

namespace VKR_Russkin.Migrations
{
    [DbContext(typeof(TeploDBContext))]
    [Migration("20250501081008_AddNewTables")]
    partial class AddNewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("VKR_Russkin.Data.DotMC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ComponentDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DotMCs");
                });

            modelBuilder.Entity("VKR_Russkin.Data.KVoA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GasTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<double>("KinematicViscosity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("KVoAs");
                });

            modelBuilder.Entity("VKR_Russkin.Data.LRC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeofLR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ValueofLR")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("LRCs");
                });

            modelBuilder.Entity("VKR_Russkin.Data.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<double>("GasFlow")
                        .HasColumnType("REAL");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("SectionLength")
                        .HasColumnType("REAL");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TemperatureLossPerMeter")
                        .HasColumnType("REAL");

                    b.Property<double>("TgasInitial")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
