// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VKR_Russkin.Data;

#nullable disable

namespace VKR_Russkin.Migrations
{
    [DbContext(typeof(TeploDBContext))]
    [Migration("20260425120000_AddRoughnessReferenceMaterials")]
    partial class AddRoughnessReferenceMaterials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
#pragma warning restore 612, 618
        }
    }
}
